### ISSUE TITLE
q contours not working in AUGD:IDE:31113(2)

### ISSUE THREAD

**Issue by bpwned** [pyIPP/ideview#1]

**Comment by bpwned** [comment]
gyro functionality breaks old shotfile entirely, should perhaps handle gracefully

```
Traceback (most recent call last):
  File "/afs/ipp/tok/soft/python27/python/2.7.9/@sys/lib/python2.7/lib-tk/Tkinter.py", line 1532, in __call__
    return self.func(*args)
  File "./ideview", line 252, in Selection
    for i in range(availablegyros):
TypeError: range() integer end argument expected, got NoneType.
```

**Comment by mverdmann** [comment]
fixed
